### ISSUE TITLE
NER 怎么使用输出ner对应标签

### ISSUE THREAD

**Issue by lonngxiang** [ckiplab/ckip-transformers#15]
from transformers import (
  BertTokenizerFast,
  AutoModel,
)

tokenizer = BertTokenizerFast.from_pretrained('bert-base-chinese')
model = AutoModel.from_pretrained('ckiplab/bert-base-chinese-ner')

。。。
这后面应该怎么写呢，才能对应输出这种
![image](https://user-images.githubusercontent.com/40717349/147812337-d0c20ec1-900f-4240-9d66-b626203aaa94.png)

**Comment by emfomy** [comment]
關於標記的轉換，可使用 CKIP Transformers 的 [NLP Tools](https://github.com/ckiplab/ckip-transformers#nlp-tools) 進行轉換。

至於詳細的 ID 對應，可參見 huggingface 的 model config 檔案 （如 https://huggingface.co/ckiplab/bert-base-chinese-ner/blob/main/config.json）。
