### ISSUE TITLE
max_length in README is not correct?

### ISSUE THREAD

**Issue by caterpillar0111** [ckiplab/ckip-transformers#16]
Hi, thanks for your great work.
I found a tiny error for your example, when execute the code
`ws = ws_driver(text, batch_size=256, max_length=512)`
It would show the error message is that
"AssertionError: Sequence length is longer than the maximum sequence length for this model (512 > 510)."
Set the max_length lower than 510 can fix this.
Without that, everything is fine. It's a excellent and convenience tool for extract information from data.

**Comment by emfomy** [comment]
The example is wrong. Fixed in [v0.2.8](https://github.com/ckiplab/ckip-transformers/releases/tag/0.2.8).
