### ISSUE TITLE
Output的embedding獲取

### ISSUE THREAD

**Issue by world4jason** [ckiplab/ckip-transformers#18]
您好：
想請教一下在使用CkipWordSegmenter, CkipPosTagger, CkipNerChunker
能從結果中獲取每一個output的embedding嗎?

像是範例中的字串長度為45的句子
`傅達仁今將執行安樂死，卻突然爆出自己20年前遭緯來體育台封殺，他不懂自己哪裡得罪到電視台。`
最終輸出時可以從某地方得到45x768這樣的結果嗎? 謝謝

**Comment by emfomy** [comment]
目前的 library 並未回傳 output embedding ，請參考[原始碼](https://ckip-transformers.readthedocs.io/en/stable/_modules/ckip_transformers/nlp/util.html#CkipTokenClassification) 修改並輸出所需的 embedding。
預計未來會加入相關的功能。
