### ISSUE TITLE
如何使用fine-tuned完的model

### ISSUE THREAD

**Issue by TaRienAce** [ckiplab/ckip-transformers#22]
您好:

想請教一下我目前利用了您在說明中提到的範例檔run_ner.py來去依照我自己的資料集微調完model了
[https://github.com/huggingface/transformers/tree/main/examples/pytorch/token-classification](https://github.com/huggingface/transformers/tree/main/examples/pytorch/token-classification)

最後分別生成了config.json以及tf_model.h5兩個檔案

但是當我想使用使用自己微調過的model時
在這行 
`ws_driver = CkipNerChunker(model="tmp/tf_model.h5")`
跳出了以下錯誤

Traceback (most recent call last):
  File "/root/miniconda3/envs/chatbot/lib/python3.6/site-packages/ckip_transformers/nlp/util.py", line 89, in _get_model_name
    model_name = self._model_names[model]
KeyError: './tmp/tf_model.h5'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Transformers_pretrained.py", line 12, in <module>
    ws_driver  = CkipWordSegmenter(model="./tmp/tf_model.h5")
  File "/root/miniconda3/envs/chatbot/lib/python3.6/site-packages/ckip_transformers/nlp/driver.py", line 52, in __init__
    model_name = kwargs.pop("model_name", self._get_model_name(model))
  File "/root/miniconda3/envs/chatbot/lib/python3.6/site-packages/ckip_transformers/nlp/util.py", line 91, in _get_model_name
    raise KeyError(f"Invalid model {model}") from exc
KeyError: 'Invalid model ./tmp/tf_model.h5'

請問我該如何正確地使用我自己微調完的model搭配CkipWordSegmenter, CkipPosTagger以及CkipNerChunker呢

**Comment by emfomy** [comment]
要使用自己微調的 model，請使用 model_name 而非 model。

`ws_driver = CkipNerChunker(model_name="tmp/tf_model.h5")`

**Comment by TaRienAce** [comment]
您好

首先非常感謝您的回覆，我後面注意到了
且我一開始是使用tensorflow微調的model
後面查看了一下先前的issue，發現好像只能使用Pytorch的run_ner.py來去微調
不過這部分我已經成功了

但目前在使用上仍有個問題是，我微調完的model，在使用
`ws_driver  = CkipWordSegmenter(model_name="pytorch_ner_model")
pos_driver = CkipPosTagger(model_name="pytorch_ner_model")`
接沒有問題都能正確斷詞與跑出結果(pytorch_ner_model是我自己的model path)

但再ner的任務中，我按照範例嘗試使用了
`ner_driver = CkipNerChunker(model_name="pytorch_ner_model")
ner = ner_driver(example, use_delim=True)`
回傳的結果ner裡面卻是空的
有沒有什麼可能發生這樣的情況可供參考呢

**Comment by emfomy** [comment]
這邊有可能的錯誤是你的模型的 label 與 CkipNerChunker 預期的格式不符合
CkipNerChunker 使用的是 BIOES https://en.wikipedia.org/wiki/Inside–outside–beginning_(tagging) 格式

**Comment by TaRienAce** [comment]
好的，我了解了
那在請問一下，斷詞的方式會有差嗎 
我目前dataset的label方式是將每個中文字一個一個拆開
並去給予BIO標記

**Comment by emfomy** [comment]
斷詞的部分僅使用 B 、 I 兩種標記
