### ISSUE TITLE
请问POS任务中识别出的标签=Neu是什么意思呢

### ISSUE THREAD

**Issue by rewonderful** [ckiplab/ckip-transformers#25]
请问POS任务中识别出的标签=Neu是什么意思呢，指连串的数字？

**Comment by emfomy** [comment]
以下是完整的標記列表
https://ckipnlp.readthedocs.io/en/latest/main/tag.html#part-of-speech-tags

**Comment by emfomy** [comment]
Fixed in [v0.3.3](https://github.com/ckiplab/ckip-transformers/releases/tag/0.3.3).
