### ISSUE TITLE
請問finetune模型前，有辦法更改模型原有label的個數嗎

### ISSUE THREAD

**Issue by andylee40** [ckiplab/ckip-transformers#28]
您好，我想要微調ckiplab/bert-base-chinese-ner這個模型，但看到模型的label有72個，有辦法從72個label中選我會使用到的29個，然後再進行微調嗎？

**Comment by emfomy** [comment]
你可以直接忽視沒在用的 label。
如果在乎效率或空間問題，可以修改最後一層的 linear layer 把用不到的 weight 刪掉。
