### ISSUE TITLE
Chinese text classification model usage example

### ISSUE THREAD

**Issue by Gelassen** [ckiplab/ckip-transformers#31]
Hello, 

Can you share please an example how to use your model to split Chinese text into separate words? 

At this moment this code:
```
from transformers import (
   BertTokenizerFast,
   AutoModelForMaskedLM,
   AutoModelForCausalLM,
   AutoModelForTokenClassification,
)

# casual language model (GPT2)
tokenizer = BertTokenizerFast.from_pretrained('bert-base-chinese')
model = AutoModelForCausalLM.from_pretrained('ckiplab/gpt2-base-chinese') # or other models above

encoded_input = tokenizer.encode(sample_input, return_tensors="pt")
# batch = []
# batch.append(encoded_input)
predictions = model.generate(encoded_input)

tokenizer.batch_decode(predictions)
```
gives ```['[CLS] 之 后 你 看 看 了 我 的 出 版 请 告 诉 我 你 认 为 什 么 [SEP] 我']``` for ```之后你看看了我的出版请告诉我你认为什么``` input. 

At the same time your example in ```example.py``` in the repo gives correct output for my input:
```
之后你看看了我的出版请告诉我你认为什么
之后(Nd)　你(Nh)　看看(VE)　了(Di)　我(Nh)　的(DE)　出版(Nv)　请(VF)　告诉(VE)　我(Nh)　你(Nh)　认为(VE)　什么(Nep)
``` 
(in case you are interested in context of this issue, here is [google doc](https://docs.google.com/document/d/1bLJsPH6Tp_nxEuwiEW6r8pABxiPKzKUJeVeK7I2t0N8/edit?usp=sharing) with my R&D information on this task)

**Comment by emfomy** [comment]
You may refer to the source code of our NLP tools.

https://ckip-transformers.readthedocs.io/en/stable/main/readme.html#nlp-tools-usage

https://ckip-transformers.readthedocs.io/en/stable/_modules/ckip_transformers/nlp/driver.html

https://ckip-transformers.readthedocs.io/en/stable/_modules/ckip_transformers/nlp/util.html

**Comment by Gelassen** [comment]
Thank you, I figured it out earlier. Here is a code in module available for launch on the backend:
```
""" Chinese text classifier
@ref https://ckip-transformers.readthedocs.io/en/stable/main/readme.html#git
"""
import asyncio
from ckip_transformers.nlp import (
    CkipWordSegmenter, 
)


class ChineseTextClassifier:

    def __init__(self):
        self.ws_driver  = CkipWordSegmenter(model="bert-base")
        self.lock = asyncio.Lock()

    async def run_single_word_segmentation(self, text):
        async with self.lock: 
            assert(isinstance(text, list) == True)
            ws = self.ws_driver(text, use_delim=True)
            return ws
```
