### ISSUE TITLE
Import nlp tools package error

### ISSUE THREAD

**Issue by Sixy1204** [ckiplab/ckip-transformers#9]
Hello,

When I use：
from ckip_transformers.nlp import CkipWordSegmenter, CkipPosTagger, CkipNerChunker
It reports ValueError: source code string cannot contain null bytes 
<img width="362" alt="捕获" src="https://user-images.githubusercontent.com/36162926/121148611-83ec6000-c874-11eb-9380-33440f176dd8.PNG">

How to fix it？

Thanks a lot！

**Comment by emfomy** [comment]
Fixed in 0.2.6
